services:
  database:
    image: postgres
    hostname: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - prisma-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: '10m'
        max-file: '3'

  front:
    build:
      context: .
    image: nuxt-app
    container_name: nuxt-app
    ports:
      - '${FRONT_OUTPUT_PORT}:3000'
    depends_on:
      database:
        condition: service_healthy
        restart: true
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}?schema=public
    networks:
      - prisma-network

  prisma-studio:
    image: node:lts-alpine3.17
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npx prisma studio
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}?schema=public
    ports:
      - '5555:5555'
    networks:
      - prisma-network
    depends_on:
      database:
        condition: service_healthy

networks:
  prisma-network:

volumes:
  postgres_data:
